"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, UserRound, CalendarDays, Mail, Phone } from "lucide-react";

type Catalog={tenant:{id:string;name:string;currency:string;cancellationHours:number;requireDeposit:boolean;depositPercent:number};categories:Array<{id:string;name:string;services:Array<{id:string;name:string;description?:string|null;durationMin:number;priceCents:number}>}>;staff:Array<{id:string;displayName:string;bio?:string|null;serviceIds:string[]}>};
type Slot={start:string;startsAt:string;staffId:string;staffName:string};
const money=(c:number,currency="EUR")=>new Intl.NumberFormat("hr-HR",{style:"currency",currency}).format(c/100);

export default function BookingClient({slug}:{slug:string}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[step,setStep]=useState(1),[serviceId,setServiceId]=useState(""),[staffId,setStaffId]=useState("any"),[date,setDate]=useState(""),[slot,setSlot]=useState<Slot|null>(null),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(false),[done,setDone]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/public/${slug}/catalog`).then(r=>r.json()).then(setCatalog)},[slug]);
 const service=useMemo(()=>catalog?.categories.flatMap(c=>c.services).find(s=>s.id===serviceId),[catalog,serviceId]);
 const days=useMemo(()=>Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);return d}),[]);
 async function loadSlots(d:string,sid=staffId){if(!serviceId)return;setLoading(true);setSlot(null);const q=new URLSearchParams({date:d,serviceId,staffId:sid});const r=await fetch(`/api/public/${slug}/availability?${q}`);const j=await r.json();setSlots(j.slots||[]);setLoading(false)}
 function pickDate(d:Date){const iso=[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");setDate(iso);void loadSlots(iso)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!slot||!service)return;setLoading(true);setError("");const fd=new FormData(e.currentTarget);const r=await fetch(`/api/public/${slug}/appointments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:service.id,staffId:staffId==="any"?slot.staffId:staffId,startsAt:slot.startsAt,customer:{name:fd.get("name"),phone:fd.get("phone"),email:fd.get("email"),note:fd.get("note")}})});const j=await r.json();if(!r.ok){setError(j.error||"Termin nije moguće rezervirati.");setLoading(false);if(r.status===409){setStep(3);void loadSlots(date)}return}setDone(j);setStep(5);setLoading(false)}
 if(!catalog)return <div className="booking-page"><div className="booking-shell"><div className="panel">Učitavanje…</div></div></div>;
 return <div className="booking-page"><header className="booking-header"><a className="brand" href="/"><span className="brand-mark">L+</span><span>{catalog.tenant.name}</span></a><span className="muted" style={{fontSize:13}}>Sigurna rezervacija</span></header><main className="booking-shell"><div className="progress">{[1,2,3,4].map(n=><span key={n} className={step>=n?"done":""}/>)}</div><div className="booking-grid"><section className="panel">
 {step===1&&<><h1>Koju uslugu želite?</h1><p className="muted">Odaberite uslugu i odmah ćete vidjeti trajanje i cijenu.</p><div className="choices">{catalog.categories.map(cat=><div key={cat.id}><div className="muted" style={{fontSize:12,fontWeight:800,textTransform:"uppercase",margin:"18px 2px 8px"}}>{cat.name}</div>{cat.services.map(s=><button key={s.id} className={`choice ${serviceId===s.id?"selected":""}`} onClick={()=>setServiceId(s.id)}><div className="choice-main"><span className="radio"/><div><strong>{s.name}</strong><div className="muted" style={{fontSize:13,marginTop:4}}><Clock3 size={13} style={{verticalAlign:-2}}/> {s.durationMin} min{s.description?` · ${s.description}`:""}</div></div></div><strong>{money(s.priceCents,catalog.tenant.currency)}</strong></button>)}</div>)}</div><div className="step-actions"><span/><button className="btn btn-brand" disabled={!serviceId} onClick={()=>setStep(2)}>Nastavi <ArrowRight size={16}/></button></div></>}
 {step===2&&<><h1>Tko će vas primiti?</h1><p className="muted">Odaberite djelatnika ili prepustite sustavu da nađe prvi slobodan termin.</p><div className="choices"><button className={`choice ${staffId==="any"?"selected":""}`} onClick={()=>setStaffId("any")}><div className="choice-main"><span className="radio"/><div><strong>Bilo tko</strong><div className="muted" style={{fontSize:13,marginTop:4}}>Najveći izbor slobodnih termina</div></div></div><UserRound size={20}/></button>{catalog.staff.filter(s=>s.serviceIds.includes(serviceId)).map(s=><button key={s.id} className={`choice ${staffId===s.id?"selected":""}`} onClick={()=>setStaffId(s.id)}><div className="choice-main"><span className="radio"/><div><strong>{s.displayName}</strong><div className="muted" style={{fontSize:13,marginTop:4}}>{s.bio||"Djelatnik"}</div></div></div><div className="avatar" style={{width:36,height:36,fontSize:12}}>{s.displayName.split(" ").map(x=>x[0]).join("").slice(0,2)}</div></button>)}</div><div className="step-actions"><button className="btn" onClick={()=>setStep(1)}><ArrowLeft size={16}/> Natrag</button><button className="btn btn-brand" onClick={()=>setStep(3)}>Odaberi vrijeme <ArrowRight size={16}/></button></div></>}
 {step===3&&<><h1>Kada vam odgovara?</h1><p className="muted">Prikazujemo samo termine koji su stvarno slobodni.</p><div className="calendar-strip">{days.slice(0,7).map(d=>{const iso=[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");return <button key={iso} className={`day ${date===iso?"active":""}`} onClick={()=>pickDate(d)}><small>{d.toLocaleDateString("hr-HR",{weekday:"short"})}</small><strong>{d.getDate()}</strong><small>{d.toLocaleDateString("hr-HR",{month:"short"})}</small></button>})}</div>{loading?<div className="empty">Tražim slobodne termine…</div>:date&&slots.length===0?<div className="empty">Nema slobodnih termina taj dan. Odaberite drugi datum.</div>:<div className="slot-grid">{slots.map(s=><button key={`${s.startsAt}-${s.staffId}`} className={`time-btn ${slot?.startsAt===s.startsAt&&slot.staffId===s.staffId?"active":""}`} onClick={()=>setSlot(s)}>{s.start}</button>)}</div>}<div className="step-actions"><button className="btn" onClick={()=>setStep(2)}><ArrowLeft size={16}/> Natrag</button><button className="btn btn-brand" disabled={!slot} onClick={()=>setStep(4)}>Moji podaci <ArrowRight size={16}/></button></div></>}
 {step===4&&<><h1>Još samo vaši podaci.</h1><p className="muted">Na email šaljemo potvrdu i link za otkazivanje ili promjenu termina.</p><form onSubmit={submit}><div className="form-grid"><div className="field wide"><label>Ime i prezime</label><input className="input" name="name" required minLength={2} placeholder="Ana Horvat"/></div><div className="field"><label><Phone size={13}/> Telefon</label><input className="input" name="phone" required placeholder="091 123 4567"/></div><div className="field"><label><Mail size={13}/> Email</label><input className="input" type="email" name="email" placeholder="ana@email.com"/></div><div className="field wide"><label>Napomena (opcionalno)</label><textarea className="input" name="note" rows={3} placeholder="Npr. osjetljivo vlasište…"/></div></div>{error&&<div className="error">{error}</div>}<p className="muted" style={{fontSize:12}}>Besplatno online otkazivanje moguće je do {catalog.tenant.cancellationHours} h prije termina.</p><div className="step-actions"><button type="button" className="btn" onClick={()=>setStep(3)}><ArrowLeft size={16}/> Natrag</button><button className="btn btn-brand" disabled={loading}>{loading?"Spremam…":catalog.tenant.requireDeposit?"Rezerviraj i plati akontaciju":"Potvrdi rezervaciju"} <Check size={16}/></button></div></form></>}
 {step===5&&<div className="success-box"><div className="success-icon"><Check/></div><h1>Termin je rezerviran!</h1><p className="muted">Potvrda je spremljena. Ako ste upisali email, stići će vam potvrda i podsjetnik prije termina.</p>{done?.requiresPayment&&<div className="error" style={{background:"#fff8e8",color:"#8a6417"}}>Akontacija od {money(done.depositCents,catalog.tenant.currency)} čeka plaćanje. Stripe Payment Element spaja se nakon unosa produkcijskih Stripe ključeva.</div>}<a className="btn btn-primary" href={done?.manageUrl}>Upravljaj terminom</a></div>}
 </section><aside className="panel summary"><h3 style={{marginTop:0}}>Vaša rezervacija</h3><div className="summary-line"><span className="muted">Usluga</span><strong>{service?.name||"—"}</strong></div><div className="summary-line"><span className="muted">Djelatnik</span><strong>{slot?.staffName||(staffId==="any"?"Bilo tko":catalog.staff.find(s=>s.id===staffId)?.displayName)||"—"}</strong></div><div className="summary-line"><span className="muted">Datum</span><strong>{date?new Date(`${date}T12:00:00`).toLocaleDateString("hr-HR",{day:"numeric",month:"short"}):"—"}</strong></div><div className="summary-line"><span className="muted">Vrijeme</span><strong>{slot?.start||"—"}</strong></div><div className="summary-line"><span className="muted">Cijena</span><strong>{service?money(service.priceCents,catalog.tenant.currency):"—"}</strong></div></aside></div></main></div>
}
