"use client";
import { useState } from "react";
type A={id:string;startsAt:string;endsAt:string;customer:{name:string};service:{name:string};staff:{id:string;displayName:string;color:string|null}};
type S={id:string;displayName:string;color:string|null};
export function CalendarBoard({initial,staff,days}:{initial:A[];staff:S[];days:string[]}){
 const [rows,setRows]=useState(initial),[msg,setMsg]=useState("");
 async function move(id:string,day:string,hour:number,staffId:string){const old=rows.find(a=>a.id===id);if(!old)return;const start=new Date(`${day}T${String(hour).padStart(2,"0")}:00:00`);const duration=new Date(old.endsAt).getTime()-new Date(old.startsAt).getTime();const optimistic=rows.map(a=>a.id===id?{...a,startsAt:start.toISOString(),endsAt:new Date(start.getTime()+duration).toISOString(),staff:{...a.staff,id:staffId,displayName:staff.find(s=>s.id===staffId)?.displayName||a.staff.displayName}}:a);setRows(optimistic);const r=await fetch(`/api/admin/appointments/${id}/move`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({startsAt:start.toISOString(),staffId})});if(!r.ok){setRows(rows);setMsg("Termin nije moguće pomaknuti na to vrijeme — slot je zauzet.")}else setMsg("Termin pomaknut.");setTimeout(()=>setMsg(""),2500)}
 return <>{msg&&<div className="error" style={{marginBottom:12,background:msg.includes("pomaknut")?"#eaf8f1":"#fff0f2",color:msg.includes("pomaknut")?"#16774f":"#b22d46"}}>{msg}</div>}<div className="table-card scroll-x"><div className="week-calendar"><div className="cal-cell cal-head">Vrijeme</div>{days.map(d=><div className="cal-cell cal-head" key={d}>{new Date(`${d}T12:00:00`).toLocaleDateString("hr-HR",{weekday:"short",day:"numeric",month:"short"})}</div>)}{Array.from({length:11},(_,i)=>8+i).flatMap(hour=>[<div className="cal-cell cal-time" key={`t${hour}`}>{String(hour).padStart(2,"0")}:00</div>,...days.map(day=><div className="cal-cell" key={`${day}-${hour}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{const [id,staffId]=e.dataTransfer.getData("text/plain").split("|");if(id)void move(id,day,hour,staffId)}}>{rows.filter(a=>{const d=new Date(a.startsAt);const local=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;return local===day&&d.getHours()===hour}).map(a=><div className="event" draggable key={a.id} onDragStart={e=>e.dataTransfer.setData("text/plain",`${a.id}|${a.staff.id}`)} title="Povucite termin na drugi sat"><strong>{new Date(a.startsAt).toLocaleTimeString("hr-HR",{hour:"2-digit",minute:"2-digit"})}</strong> {a.customer.name}<div style={{opacity:.75,marginTop:3}}>{a.service.name} · {a.staff.displayName}</div></div>)}</div>)])}</div></div><div className="muted" style={{fontSize:12,marginTop:9}}>Savjet: povucite termin na drugi sat za brzo pomicanje. Za promjenu djelatnika koristit ćemo detaljni modal u sljedećem UI koraku.</div></>
}
